/* This file is generated by scripts/write-build-info.mjs. */
export const BUILD_INFO = {
  commitSha: "fc3d24aad2d7132530b13f4f0aa73262ee92b2ea",
  branch: "main",
  buildId: undefined,
  buildTime: "2026-07-27T20:22:20.925Z",
} as const;
