/* This file is generated by scripts/write-build-info.mjs. */
export const BUILD_INFO = {
  commitSha: "6784d0bd041b38a6b87b97d6c804cf1825651baa",
  branch: "main",
  buildId: undefined,
  buildTime: "2026-07-22T17:54:54.099Z",
} as const;
