/* This file is generated by scripts/write-build-info.mjs. */
export const BUILD_INFO = {
  commitSha: "19aa5c8f73fe93cc1cb38f5911f524468db37692",
  branch: "main",
  buildId: undefined,
  buildTime: "2026-07-26T06:44:07.426Z",
} as const;
