export interface TemplatePreset {
  id: string;
  nameZh: string;
  nameEn: string;
  templateZh: string;
  templateEn: string;
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: "pre_open",
    nameZh: "开盘前简报",
    nameEn: "Pre-open brief",
    templateZh: [
      "# GlobalPulse 开盘前简报",
      "",
      "- 时间：{{generatedAt}}（{{timezone}}）",
      "- 主题：{{topicQuery}}",
      "",
      "## 市场速览",
      "{{marketReport}}",
      "",
      "## 今日关注",
      "{{itemsMarkdown}}",
      "",
      "> 来源：{{sourceUrl}}",
    ].join("\n"),
    templateEn: [
      "# GlobalPulse Pre-Open Brief",
      "",
      "- Time: {{generatedAt}} ({{timezone}})",
      "- Focus: {{topicQuery}}",
      "",
      "## Market snapshot",
      "{{marketReport}}",
      "",
      "## Watchlist",
      "{{itemsMarkdown}}",
      "",
      "> Source: {{sourceUrl}}",
    ].join("\n"),
  },
  {
    id: "post_close",
    nameZh: "收盘后复盘",
    nameEn: "Post-close recap",
    templateZh: [
      "# GlobalPulse 收盘复盘",
      "",
      "- 时间：{{generatedAt}}（{{timezone}}）",
      "- 主题：{{topicQuery}}",
      "",
      "## 收盘要点",
      "{{marketReport}}",
      "",
      "## 新闻与催化",
      "{{itemsMarkdown}}",
      "",
      "> 来源：{{sourceUrl}}",
    ].join("\n"),
    templateEn: [
      "# GlobalPulse Post-Close Recap",
      "",
      "- Time: {{generatedAt}} ({{timezone}})",
      "- Focus: {{topicQuery}}",
      "",
      "## Session takeaways",
      "{{marketReport}}",
      "",
      "## News & catalysts",
      "{{itemsMarkdown}}",
      "",
      "> Source: {{sourceUrl}}",
    ].join("\n"),
  },
  {
    id: "crypto_morning",
    nameZh: "加密早报",
    nameEn: "Crypto morning",
    templateZh: [
      "# GlobalPulse 加密早报",
      "",
      "- 时间：{{generatedAt}}（{{timezone}}）",
      "- 主题：{{topicQuery}}",
      "",
      "## 行情",
      "{{marketReport}}",
      "",
      "## 热点",
      "{{itemsMarkdown}}",
      "",
      "> 来源：{{sourceUrl}}",
    ].join("\n"),
    templateEn: [
      "# GlobalPulse Crypto Morning",
      "",
      "- Time: {{generatedAt}} ({{timezone}})",
      "- Focus: {{topicQuery}}",
      "",
      "## Markets",
      "{{marketReport}}",
      "",
      "## Headlines",
      "{{itemsMarkdown}}",
      "",
      "> Source: {{sourceUrl}}",
    ].join("\n"),
  },
  {
    id: "daily_hot",
    nameZh: "每日热点",
    nameEn: "Daily hotspot",
    templateZh: [
      "# GlobalPulse 每日热点",
      "",
      "- 时间：{{generatedAt}}（{{timezone}}）",
      "- 主题：{{topicQuery}}",
      "",
      "{{itemsMarkdown}}",
      "",
      "> 来源：{{sourceUrl}}",
    ].join("\n"),
    templateEn: [
      "# GlobalPulse Daily Hotspots",
      "",
      "- Time: {{generatedAt}} ({{timezone}})",
      "- Focus: {{topicQuery}}",
      "",
      "{{itemsMarkdown}}",
      "",
      "> Source: {{sourceUrl}}",
    ].join("\n"),
  },
];
