import type { OutputFormat, PulseSchedule } from "./config";
import type { TopicItem } from "./sources";

export interface DigestContext {
  generatedAt: string;
  timezone: string;
  topicQuery: string;
  sourceUrl: string;
  items: TopicItem[];
  format: OutputFormat;
  marketReport?: string;
}

export function renderDigest(schedule: PulseSchedule, context: DigestContext): { title: string; body: string } {
  const displayItems = context.items.slice(0, schedule.reportType === "daily_hot" ? 28 : 6);
  const title = schedule.language === "zh" ? `GlobalPulse：${schedule.name}` : `GlobalPulse: ${schedule.name}`;
  if (schedule.reportType === "daily_hot") return { title, body: renderDailyHotBody(schedule, context, displayItems) };

  const variables: Record<string, string> = {
    generatedAt: context.generatedAt,
    timezone: context.timezone,
    topicQuery: context.topicQuery,
    sourceUrl: context.sourceUrl,
    itemsMarkdown: renderItemsMarkdown(displayItems, schedule),
    itemsText: renderItemsText(displayItems, schedule),
    itemsJson: JSON.stringify(displayItems, null, 2),
    marketReport: context.marketReport ?? "",
  };
  return { title, body: renderByFormat(schedule.template, variables, context.format) };
}

function renderDailyHotBody(schedule: PulseSchedule, context: DigestContext, items: TopicItem[]): string {
  if (context.format === "json") {
    return JSON.stringify({ type: "daily_hot", generatedAt: context.generatedAt, timezone: context.timezone, topicQuery: context.topicQuery, sourceUrl: context.sourceUrl, items }, null, 2);
  }

  const zh = schedule.language === "zh";
  const grouped = groupItemsBySection(items);
  const globalItems = grouped.global.slice(0, 6);
  const domesticItems = grouped.domestic.slice(0, 6);
  const socialItems = grouped.platform.slice(0, 10);
  const marketItems = pickByCategory(items, ["macro", "finance", "market", "crypto-sentiment"], 6);
  const techItems = pickByCategory(items, ["industry", "technology", "tech", "international-tech"], 6);
  const watchItems = [...items].sort((a, b) => (b.score ?? 0) - (a.score ?? 0)).slice(0, 4);
  const used = [...globalItems, ...domesticItems, ...socialItems, ...marketItems, ...techItems, ...watchItems];
  const moreItems = items.filter((item) => !used.some((shown) => isSameTopicItem(item, shown))).slice(0, Math.max(0, 28 - used.length));

  const lines = [
    zh ? "# GlobalPulse 热点简报" : "# GlobalPulse Hot Brief",
    "",
    zh ? `- 生成时间：${context.generatedAt}` : `- Generated: ${context.generatedAt}`,
    zh ? `- 时区：${context.timezone}` : `- Timezone: ${context.timezone}`,
    zh ? `- 关注方向：${context.topicQuery}` : `- Focus: ${context.topicQuery}`,
    "",
    zh ? "## 🧭 今日总览" : "## 🧭 Executive Summary",
    "",
    ...renderOverview(items, schedule),
    "",
  ];

  appendSection(lines, zh ? "## 🌍 全球热点" : "## 🌍 Global Headlines", globalItems, schedule, "global");
  appendSection(lines, zh ? "## 🇨🇳 中国热点" : "## 🇨🇳 China Highlights", domesticItems, schedule, "domestic");
  appendSection(lines, zh ? "## 💹 财经与市场" : "## 💹 Markets & Macro", marketItems, schedule, "market");
  appendSection(lines, zh ? "## 🤖 科技与产业" : "## 🤖 Tech & Industry", techItems, schedule, "tech");
  appendSection(lines, zh ? "## 🔥 社交平台热搜" : "## 🔥 Social Trends", socialItems, schedule, "social");
  appendSection(lines, zh ? "## 📌 重点观察" : "## 📌 What to Watch", watchItems, schedule, "watch");
  appendSection(lines, zh ? "## 🗞️ 更多重点" : "## 🗞️ More Key Items", moreItems, schedule, "more");

  lines.push("", zh ? `> 数据来源：${context.sourceUrl}` : `> Sources: ${context.sourceUrl}`);
  lines.push(zh ? "> 本报告由 GlobalPulse 自动生成。原文入口统一使用“查看原文”超链接，正文不直接展示裸链接。" : "> Generated by GlobalPulse. Source URLs are shown as clickable text links.");

  const markdown = lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
  return context.format === "text" ? markdownToText(markdown) : markdown;
}

function renderOverview(items: TopicItem[], schedule: PulseSchedule): string[] {
  const zh = schedule.language === "zh";
  if (!items.length) return [zh ? "- 暂无足够热点数据，请检查新闻源、热榜源或 API 配置。" : "- Not enough live items were collected. Please check source settings."];
  const top = items.slice(0, 3).map((item) => item.title).join("；");
  const keywords = extractKeywords(items).join("、") || (zh ? "全球热点、政策、市场、科技、社会讨论" : "global, policy, markets, technology, society");
  return zh ? [
    `- 本次共聚合 ${items.length} 条候选热点，覆盖全球新闻、中国热点、市场宏观、科技产业和社交热搜。`,
    `- 当前最值得先看的事件包括：${top}。`,
    `- 关键词：${keywords}。`,
    "- 阅读建议：先看“重点观察”和“财经与市场”，再按兴趣点击每条新闻的“查看原文”继续阅读。",
  ] : [
    `- ${items.length} candidate items were collected across global news, China, markets, technology, and social trends.`,
    `- Top items: ${top}.`,
    `- Keywords: ${keywords}.`,
    "- Start with “What to Watch” and “Markets & Macro”, then open source links for deeper reading.",
  ];
}

function appendSection(lines: string[], heading: string, items: TopicItem[], schedule: PulseSchedule, type: string): void {
  if (!items.length) return;
  lines.push(heading, "", renderDailyHotItems(items, schedule, type), "");
}

function renderDailyHotItems(items: TopicItem[], schedule: PulseSchedule, type: string): string {
  return items.map((item, index) => {
    const source = item.source ? ` · 来源：${escapeMarkdown(item.source)}` : "";
    const heat = typeof item.score === "number" ? ` · 热度 ${Math.round(item.score)}` : "";
    const summary = item.summary ? `\n   摘要：${escapeMarkdown(item.summary)}` : "";
    const note = inferDailyHotNote(item, schedule, type);
    const noteLine = note ? `\n   ${note}` : "";
    const link = normalizeHttpUrl(item.url) ? `\n   [查看原文](${normalizeHttpUrl(item.url)})` : "";
    return `${index + 1}. **${escapeMarkdown(item.title)}**${source}${heat}${summary}${noteLine}${link}`;
  }).join("\n");
}

function inferDailyHotNote(item: TopicItem, schedule: PulseSchedule, type: string): string | undefined {
  if (schedule.language !== "zh") return undefined;
  const category = item.category ?? "global-news";
  if (type === "social") return "热搜解读：属于当前公共讨论热点，关注是否继续发酵或影响品牌、监管、消费情绪。";
  if (type === "watch") return "后续看点：关注事件进展、官方表态、市场反应以及是否出现二次传播。";
  if (type === "market" || category === "macro" || category === "finance") return "可能影响：关注利率、汇率、风险偏好、大宗商品和权益市场联动。";
  if (type === "tech" || category === "industry") return "为什么值得关注：可能影响产业链竞争格局、企业投资方向和中长期增长预期。";
  if (category === "geopolitics") return "观察点：可能影响地区安全、能源价格、供应链稳定和国际关系走向。";
  if (category === "policy") return "观察点：可能改变监管预期、财政支出方向、产业扶持力度或跨境关系。";
  return "观察点：关注后续是否演变成政策、市场、产业或社会情绪变量。";
}

function groupItemsBySection(items: TopicItem[]): { global: TopicItem[]; domestic: TopicItem[]; platform: TopicItem[] } {
  return items.reduce((acc, item) => {
    const section = item.section ?? "global";
    if (section === "domestic") acc.domestic.push(item);
    else if (section === "platform") acc.platform.push(item);
    else acc.global.push(item);
    return acc;
  }, { global: [] as TopicItem[], domestic: [] as TopicItem[], platform: [] as TopicItem[] });
}

function pickByCategory(items: TopicItem[], categories: string[], limit: number): TopicItem[] {
  const set = new Set(categories.map((item) => item.toLowerCase()));
  return items.filter((item) => item.category && set.has(item.category.toLowerCase())).slice(0, limit);
}

function isSameTopicItem(a: TopicItem, b: TopicItem | null): boolean {
  if (!b) return false;
  const au = normalizeHttpUrl(a.url);
  const bu = normalizeHttpUrl(b.url);
  if (au && bu) return au === bu;
  return a.title.trim().toLowerCase() === b.title.trim().toLowerCase();
}

function renderByFormat(template: string, variables: Record<string, string>, format: OutputFormat): string {
  if (format === "json") return JSON.stringify({ generatedAt: variables.generatedAt, timezone: variables.timezone, topicQuery: variables.topicQuery, sourceUrl: variables.sourceUrl, items: JSON.parse(variables.itemsJson ?? "[]") }, null, 2);
  const rendered = template.replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, (_, key: string) => variables[key] ?? "");
  return format === "text" ? markdownToText(rendered) : rendered;
}

function renderItemsMarkdown(items: TopicItem[], schedule: PulseSchedule): string {
  if (!items.length) return schedule.language === "zh" ? "_暂无可用热点数据。_" : "_No topic items were found._";
  return items.map((item, index) => {
    const source = item.source ? ` — ${item.source}` : "";
    const score = typeof item.score === "number" ? ` · score ${item.score}` : "";
    const category = item.category ? ` · ${item.category}` : "";
    const summary = item.summary ? `\n   ${item.summary}` : "";
    const impact = inferCatalystImpactLine(item, schedule);
    const link = normalizeHttpUrl(item.url) ? `\n   [查看原文](${normalizeHttpUrl(item.url)})` : "";
    return `${index + 1}. ${escapeMarkdown(item.title)}${source}${category}${score}${summary}${impact ? `\n   ${impact}` : ""}${link}`;
  }).join("\n");
}

function renderItemsText(items: TopicItem[], schedule: PulseSchedule): string {
  if (!items.length) return schedule.language === "zh" ? "暂无可用热点数据。" : "No topic items were found.";
  return items.map((item, index) => {
    const source = item.source ? ` - ${item.source}` : "";
    const score = typeof item.score === "number" ? ` - score ${item.score}` : "";
    const summary = item.summary ? ` - ${item.summary}` : "";
    const impact = inferCatalystImpactLine(item, schedule);
    const linkHint = normalizeHttpUrl(item.url) ? " - 查看原文" : "";
    return `${index + 1}. ${item.title}${source}${score}${summary}${impact ? ` - ${impact}` : ""}${linkHint}`;
  }).join("\n");
}

function inferCatalystImpactLine(item: TopicItem, schedule: PulseSchedule): string | undefined {
  if (schedule.language !== "zh" || schedule.reportType === "daily_hot") return undefined;
  const text = `${item.title}\n${item.summary ?? ""}`.toUpperCase();
  const score = sentimentScore(text);
  const tone = score > 0 ? "偏利多" : score < 0 ? "偏利空" : "中性";
  const focus = schedule.focusSymbols.slice(0, 3).join("、");
  const suffix = focus ? `；并关注 ${focus} 的联动反应` : "";
  if (schedule.reportType === "a_share") return score > 0 ? `盘面影响：${tone}，可能解释当前A股相关板块的相对抗跌或回升${suffix}。` : score < 0 ? `盘面影响：${tone}，可能解释当前A股风险偏好走弱与指数回落${suffix}。` : `盘面影响：${tone}，短线更多体现为情绪扰动，需结合量能确认方向${suffix}。`;
  if (schedule.reportType === "us_stock") return score > 0 ? `盘面影响：${tone}，可能支撑美股风险偏好与成长板块表现${suffix}。` : score < 0 ? `盘面影响：${tone}，可能压制美股风险偏好并推升防御情绪${suffix}。` : `盘面影响：${tone}，对指数影响有限，更多体现在结构分化${suffix}。`;
  if (schedule.reportType === "crypto") return score > 0 ? `盘面影响：${tone}，可能推动主流币与高beta币种同步走强${suffix}。` : score < 0 ? `盘面影响：${tone}，可能触发主流币回撤与杠杆去化${suffix}。` : `盘面影响：${tone}，波动可能放大但方向仍需后续催化确认${suffix}。`;
  return undefined;
}

function sentimentScore(text: string): number {
  const positive = ["利好", "增长", "超预期", "回购", "订单", "上调", "突破", "反弹", "上涨", "降息", "宽松", "BEAT", "SURGE", "RALLY", "UPGRADE", "EASING"];
  const negative = ["利空", "下滑", "下跌", "亏损", "事故", "调查", "制裁", "关税", "收紧", "通胀上行", "风险", "MISS", "DROP", "CRASH", "PROBE", "TARIFF", "TIGHTENING"];
  const hit = (words: string[]) => words.reduce((n, word) => n + (text.includes(word.toUpperCase()) ? 1 : 0), 0);
  return hit(positive) - hit(negative);
}

function extractKeywords(items: TopicItem[]): string[] {
  const dict = ["AI", "芯片", "美股", "A股", "港股", "黄金", "原油", "美元", "人民币", "比特币", "美联储", "利率", "通胀", "地缘政治", "监管", "政策", "消费", "汽车", "医药", "能源", "供应链", "社会热点", "热搜"];
  const text = items.map((item) => `${item.title} ${item.summary ?? ""} ${item.category ?? ""}`).join("\n").toLowerCase();
  return dict.filter((keyword) => text.includes(keyword.toLowerCase()));
}

function markdownToText(markdown: string): string {
  return markdown.replace(/^#+\s*/gm, "").replace(/\*\*/g, "").replace(/`/g, "").replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 - $2");
}

function escapeMarkdown(value: string): string {
  return value.replaceAll("[", "\\[").replaceAll("]", "\\]");
}

function normalizeHttpUrl(value: string): string | undefined {
  try {
    const parsed = new URL(value.trim());
    return parsed.protocol === "http:" || parsed.protocol === "https:" ? parsed.toString() : undefined;
  } catch {
    return undefined;
  }
}
